all:	message

message:  sort-A-out sort-A-in

sort-A-out:  sort-A-out.c
	cc sort-A-out.c -o sort-A-out

sort-A-in:  sort-A-in.c
	cc sort-A-in.c -o sort-A-in

sort-B-in: sort-B-in.c
	cc sort-B-in.c -o sort-B-in	

clean: 
	rm sort-A-out sort-A-in
